 Diseño de una Síntesis óptima.

Se quiere realizar una síntesis de nanpartículas de plata de la manera menos costosa y produciendo la mayuor cantidad de nanoalambres posibles. Por lo que se quiere variar la cantidad de cada reactivo necesarios para cumplir con las cantidades minimas encontradas en artículo cientifíco en el que se basa la síntesis, con el fin de obtener un resultado óptimo. Los reactivos a utilizar son PVP, etilengilicol para ayudar a la síntesis, mientras que los proveedores de plata son el nitrato de plata y el cloruro de plata, para evitar una unión entre estos compuestos y obtener un resultado fallido se agregará hidroxido de sodi que se encargar de unirse con los iones correspondientes y evitar la formación de los compuestos iniciales. Los requisitos que se tienen es que para obtener 50 gramos de nanoalambres, se necesitan al menos 78.74 gramos de nitrato de plata en base del porcentaje que contiene este de plata, pero no más de 100 gramos para evitar una aglomeración de partículas y que estas no hagan nucleación. Además se encontro que se necesitan al menos 4635 gramos de etilengilicol y finalmente 156.972 gramos de PVP para conseguir la cantidad deseada de nanoalambres.

Los porcentajes que contienen cada reactivo se pueden encontrar en la siguiente tabla:

Reactivo|Plata|PVP|EG|Sodio|
:----|----|----|----|----|
Nitrato de plata ($AgNO_3$)|63.5%|0%|0%|0%|0%|
Cloruro de plata ($AgCI$)|75.26% 0%|0%|0%|0%|
Hidroxido de Sodio ($NaOH$)|0%|0%|57.48%|0%|
PVP|  0%|100%|0%|0%|0%|
Etilengilicol|0%|0%|100%|0%|0%|


Los costos de cada reactivo son:

Reactivo|Costo por gramo
:----|----
Nitrato de plata ($AgNO_3$)|$\$$46
Cloruro de plata ($AgCI$)|$\$$28.89
Hidroxido de Sodio ($NaOH$)|$\$$0.4796
PVP|$\$$.0817|
Etilengilicol|$\$$.0225

Las variables a utilizar se pueden representar por:

+ $x_1:$ Gramos de Nitrato de plata ($AgNO_3$)  
+ $x_2:$ Gramos de Cloruro de plata  
+ $x_3:$ Gramos de Hidroxido de sodio
+ $x_4:$ Gramos de PVP
+ $x_5:$ Gramos de Etilengilicol

En base a los costos la función a optimizar es:

$46x_1+26.89x_2+0.4796x_3+0.0817x_4+0.0225x_5$

Mientras que las restricciones se representan con:

$$.635x_1+.7526x_2 \geq 50$$
$$-.2474x_1-.365x_2+.5748x_3 \geq 0$$
$$x_4 \geq 156.972$$
$$x_5 \geq 4635$$



In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

import numpy as np 
import scipy.optimize as opt

In [14]:
c=np.array([46,26.89,.4796,.0817,.0225])
A_ub=np.array([[-.635,-.7526,0,0,0],
               [-.2474,-.365,.5748,0,0],
               [0,0,0,-1,0],
               [0,0,0,0,-1]])
b_ub=np.array([-50,0,-156.972,-4635])

In [16]:
c

array([4.600e+01, 2.689e+01, 4.796e-01, 8.170e-02, 2.250e-02])

In [17]:
A_ub

array([[-0.635 , -0.7526,  0.    ,  0.    ,  0.    ],
       [-0.2474, -0.365 ,  0.5748,  0.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  1.    ,  0.    ],
       [ 0.    ,  0.    ,  0.    ,  0.    ,  1.    ]])

In [18]:
b_ub

array([  -50.   ,     0.   ,  -156.972, -4635.   ])

In [15]:
solucion_sintesis=opt.linprog(c,A_ub,b_ub)
solucion_sintesis

     con: array([], dtype=float64)
     fun: 0.0
 message: 'The problem is (trivially) infeasible because a singleton row in the upper bound constraints is inconsistent with the bounds.'
     nit: 0
   slack: array([  -50.   ,     0.   ,  -156.972, -4635.   ])
  status: 2
 success: False
       x: array([0., 0., 0., 0., 0.])